language: node_js

node_js:
  - "0.10"

script:
    - node_modules/karma/bin/karma start karma.conf.js --single-run
    - node_modules/grunt/bin/grunt test    

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g karma bower grunt-cli
  - bower install
  - npm install
